sudo: required
dist: trusty
language: java
jdk:
- oraclejdk8
before_install:
- sudo apt-get install -y maven
- wget https://download.jetbrains.com/teamcity/TeamCity-2017.1.1.tar.gz
- tar -xzf TeamCity-2017.1.1.tar.gz -C /opt
install: "/bin/true"
script: mvn -Dteamcity.distribution=/opt/TeamCity clean package
deploy:
  provider: releases
  api_key:
    secure: ZpQQqZsn/kqjAXTAjHhxJxq6/OAIHXezPHMTgo3oDlOCK0sCqnzjh7EesLxcGJzSNRAlKCB0cBGsyWpogcnoQUWdQxT00CaEvHBfKUdXUE66U+HEM5NCfSuSZQm1JhiwWncAtrXobaqlNOj38qlfA91gW3SVOXcrzQ0PUXUG7og=
  file: octopus-distribution/target/Octopus.TeamCity.zip
  on:
    repo: OctopusDeploy/Octopus-TeamCity
    tags: true
